version: '3'
services:
  web:
    build: .
    command: make docker
    volumes:
      - .:/home/app
    ports:
      - "4000:4000"
    links:
      - redis
    depends_on:
      - redis
  test:
    image: pnx_test_web
    command: make tests
    environment:
      MIX_ENV: test
      PORT: 4001
    volumes:
      - .:/home/app
  redis:
    image: redis:latest
    ports:
      - '6379:6379'